### ISSUE TITLE
Add CI support and improve integration test

### ISSUE THREAD

**Issue by AstroProfundis** [pingcap/tiup#343]
add ci:
- [x] build and static check pingcap-incubator/tiup-cluster#254 
- [x] unit test pingcap-incubator/tiup-cluster#254
- [x] integration test pingcap-incubator/tiup-cluster#255

test to cover commands:
- [x] list 
- [x] deploy
- [x] start
- [x] stop
- [x] restart
- [x] scale-in
- [x] scale-out
- [x] destroy
- [x] upgrade pingcap-incubator/tiup-cluster#275
- [x] display
- [x] audit
- [x] edit-config pingcap-incubator/tiup-cluster#291
- [x] reload pingcap-incubator/tiup-cluster#291
- [ ] import

new commands:
- [x] check pingcap-incubator/tiup-cluster#329 
- [ ] patch

Add basic command test pr:
pingcap-incubator/tiup-cluster#249 pingcap-incubator/tiup-cluster#252 

feature need
- [x] can check cluster writable pingcap-incubator/tiup-cluster#275
