### ISSUE TITLE
Support deploying and managing TLS encryption enabled TiDB cluster

### ISSUE THREAD

**Issue by lucklove** [pingcap/tiup#529]
### Description

At present, when deploying a cluster with tiup-cluster, the tidb cluster (tidb <-> pd <-> tikv and pd <-> tiup) use plain messages to communicate, this may lead to potential security leaks. We should support TLS encryption as an option in the cluster topology to enable TLS encryption among components.

Similar support is already implemented in tidb-ansible and tidb-operator.

### Catagory

Security

### Value

Increase security of TiDB cluster, and avoid potential security leaks like MITM attack.

### TODO List

 - [x] Add support of TLS encryption in specs
    - [x] PD
    - [x] TiKV
    - [x] TiDB (Both server and client)
    - [x] Pump / Drainer
    - [x] CDC
    - [ ] binlog
    - [x] Conflict validation with unsupported components
 - [x] Generate TLS certificates and correct configs for components
 - [x] Support API calls with TLS encryption enabled

### Schedule

GanttStart: 2020-08-01
GanttDue: 2020-08-31
GanttProgress: 95%

**Comment by overvenus** [comment]
Reminder: Please also support TiCDC TLS deployment.

**Comment by lucklove** [comment]
It seems `TiFlash` and `TiSpark` don't support TLS, they may be disabled once the user enables TLS.

**Comment by july2993** [comment]
> Reminder: Please also support TiCDC TLS deployment.

also tidb binog

**Comment by AstroProfundis** [comment]
@july2993 @overvenus Is there any doc about how to configure TLS for CDC and binlog?

**Comment by nolouch** [comment]
This issue has been placed in the security issue https://github.com/pingcap/tidb/issues/18084 as a sub-item.  It's duplicated in `longterm P0 Backlog Kanban`, maybe we can move out it and place it in team's kanban.

**Comment by overvenus** [comment]
@AstroProfundis 
TiCDC TLS (Chinese version) https://docs.pingcap.com/zh/tidb/stable/manage-ticdc#%E4%BD%BF%E7%94%A8%E5%8A%A0%E5%AF%86%E4%BC%A0%E8%BE%93-tls-%E5%8A%9F%E8%83%BD

**Comment by uglyengineer** [comment]
@lonng this is a sub-task of tidb#18084, do not adding it to longterm project.

**Comment by ilovesoup** [comment]
Actually this issue is about "support deploy cluster with security features enabled" instead of "support those security features among components". Please have title and description clear, or it is a waste of time for whom cares. @lucklove
