### ISSUE TITLE
support deploy and manage dm 2.0 

### ISSUE THREAD

**Issue by july2993** [pingcap/tiup#557]
### Description

At first, we had supported deploy dm but later was changed to work on the `dms` now, we abandon the `dms`
and need to support deploy dm directly again.

Thinks we need to do mainly:
- try revert some code make it works, mainly ref: https://github.com/pingcap/tiup/pull/490
- also, refactor the code because the codes are mainly copied from the cluster containing too much duplicate and useless code.

### Category
new component/new feature

### Value
better easy to use compare to DM-Ansible

### TODO list

relate issues:

- [x] Should not use the same directory of tiup-cluster to save meta, will conflict if using the save cluster name, we can encapsulate the logic about metafiles. #567 
~~- [ ] refactor codes in topology_dm.go to avoid much duplicate code with the one that cluster use.~~
- [x] support monitor(p8s and grafana) #656 
~~- [ ] avoid use `bin/bin/` in the deploy dir~~
- [x] support import from ansible with 1.* and upgrade to 2.0 #672 #724 
- [x] add relate integration tests #629 
- [x] add docs https://github.com/pingcap/docs-dm/pull/225
- [x] reject deploy < 2.0 version #645 
- [x] remove dm-portal support since it's deprecated in plan by DM team #629 
- [x] update `examples/topology.dm.example.yaml` #679
...

support commands(#587):
- [x] deploy
- [x] start
- [x] stop
- [x] restart
- [x] destroy
- [x] exec
- [x] list 
- [x] upgrade
- [x] patch
- [x] scale-in/scale-out
- [x] edit config
- [x] reload
- [x] display

### Documentations
- TODO

### Schedule
GanttStart: 2020-07-01
GanttDue: 2020-08-31
GanttProgress: 100%
